#æ³¨: æ·»åŠ #å·ä»£è¡¨æ³¨é‡Šè¯æ¡,ç”¨äºç†è§£åŠŸèƒ½,éƒ¨åˆ†#å·æ˜¯ç”¨æ¥æš‚æ—¶å±è”½æŸäº›åŠŸèƒ½,å¯åˆ (å…·ä½“æƒ…å†µå…·ä½“åˆ†æ)
proxy-providers:
  provider1:
#æŠŠå¤åˆ¶çš„ç¬¬ä¸€ä¸ªè®¢é˜…åœ°å€ç²˜è´´åˆ° url é‡Œ
    url: ""
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
      timeout: 5000
      lazy: true
    override:
      tfo: true
      mptcp: false
      udp: true
      udp-over-tcp: false
      down: "100 Mbps"
      up: "10 Mbps"
      skip-cert-verify: true
      ip-version: ipv6-prefer
#åœ¨additional-prefixé‡Œåé¢å¡«å†™æœºåœºåç§°æˆ–è€…ä¸ºç©º
      additional-prefix: ""

  provider2:
#æŠŠå¤åˆ¶çš„ç¬¬äºŒä¸ªè®¢é˜…åœ°å€ç²˜è´´åˆ° url é‡Œ,å¦‚æœæ²¡æœ‰å°±ç©ºç€
    url: ""
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
      timeout: 5000
      lazy: true
    override:
      tfo: true
      mptcp: false
      udp: true
      udp-over-tcp: false
      down: "100 Mbps"
      up: "10 Mbps"
      skip-cert-verify: true
      ip-version: ipv6-prefer
#åœ¨additional-prefixé‡Œå¡«å†™æœºåœºåç§°æˆ–è€…ä¸ºç©º(æ³¨:ä¸èƒ½ä¸ç¬¬ä¸€ä¸ªæœºåœºé‡å)
      additional-prefix: ""

port: 7891
socks-port: 7892
mixed-port: 7890
ipv6: true
allow-lan: true
lan-allowed-ips:
  - 0.0.0.0/0
  - ::/0
skip-auth-prefixes:
  - 127.0.0.1/8
  - ::1/128
bind-address: "*"
mode: rule
log-level: error
unified-delay: true
keep-alive-interval: 15
keep-alive-idle: 15
disable-keep-alive: false
tcp-concurrent: true

external-controller: 127.0.0.1:9090
external-controller-cors:
  allow-origins:
    - '*'
  allow-private-network: true
external-ui: ui
external-ui-name: xd
secret: ""
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

find-process-mode: always
global-client-fingerprint: chrome
global-ua: clash.meta

profile:
  store-selected: true
  store-fake-ip: true

#åˆ†éš”  æ­¤ä¸ºGeoDataåŠŸèƒ½,å¦‚æœ‰éœ€è¦å°±æŠŠä»¥ä¸‹çš„æ‰€æœ‰#å·åˆ æ‰å³å¯
#geodata-mode: false
#geodata-loader: memconservative
#geo-auto-update: false
#geo-update-interval: 24
#geox-url:
  #geoip: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  #geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  #mmdb: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.metadb"
  #asn: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"
etag-support: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
      override-destination: null
    QUIC:
      ports: [443, 8443]
      override-destination: null
  force-domain:
    - +.v2ex.com
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"
  skip-src-address:
    - 192.168.0.3/32
  skip-dst-address:
    - 192.168.0.3/32

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - any:53
    - tcp://any:53
  device: mihomo
  mtu: 4000
  strict-route: true
  gso: true
  gso-max-size: 65536
  udp-timeout: 300
#åˆ†éš”  ç‹¬ç«‹äºç«¯ç‚¹çš„NAT,æ²¡äº‹åˆ«å¼€
  endpoint-independent-nat: false

  auto-route: true
  iproute2-table-index: 2022
  iproute2-rule-index: 9000
  auto-redirect: true
  auto-detect-interface: true

dns:
  enable: true
  cache-algorithm: arc
  prefer-h3: true
  use-hosts: true
  use-system-hosts: true
#åˆ†éš”  è¿æ¥éµå®ˆè·¯ç”±è§„åˆ™,ä¸å»ºè®®å’Œ"prefer-h3"ä¸€èµ·ä½¿ç”¨
  respect-rules: false

  ipv6: true
  ipv6-timeout: 300
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-range6: fdfe:dcba:9876::1/64
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "+.market.xiaomi.com"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time-ios.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '*.pool.ntp.org'
    - +.services.googleapis.cn
    - +.push.apple.com
    - time1.cloud.tencent.com
    - localhost.ptlogin2.qq.com
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - lens.l.google.com
    - '*.n.n.srv.nintendo.net'
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - '*.*.xboxlive.com'
    - '*.msftncsi.com'
    - '*.msftconnecttest.com'
    - '*.mcdn.bilivideo.cn'
    - +.bilibili.com
    - +.bilicdn.com
    - +.bilivideo.com
    - WORKGROUP
  nameserver-policy: null
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 8.8.8.8
    - 8.8.4.4
    - 1.0.0.1
    - 1.1.1.1
    - tls://223.5.5.5
    - tls://223.6.6.6
    - system
  nameserver:
    - 223.5.5.5
    - 180.76.76.76
    - 119.29.29.29
    - 117.50.11.11
    - 117.50.10.10
    - 114.114.114.114
    - 8.8.8.8
    - 8.8.4.4
    - 1.0.0.1
    - 1.1.1.1
    - tls://223.5.5.5:853
    - tls://8.8.8.8
    - tls://8.8.4.4
    - tls://1.0.0.1
    - tls://1.1.1.1
    - quic://dns.adguard.com:784
    - https://doh.pub/dns-query
    - https://223.5.5.5/dns-query
    - https://dns.alidns.com/dns-query
    - https://doh.360.cn/dns-query
    - https://mozilla.cloudflare-dns.com/dns-query
    - system
  fallback:
    - 8.8.8.8
    - 8.8.4.4
    - 1.1.1.1
    - tls://8.8.4.4:853
    - tls://1.1.1.1
    - tls://dns.rubyfish.cn:853
    - tls://1.0.0.1:853
    - tls://dns.google:853
    - https://1.0.0.1/dns-query
    - https://dns.rubyfish.cn/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
  direct-nameserver-follow-policy: false
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
    geosite:
      - gfw

ntp:
  enable: false
  write-to-system: true
  server: time.apple.com
  port: 123
  interval: 30

experimental:
  quic-go-disable-gso: false
  quic-go-disable-ecn: true
  dialer-ip4p-convert: false
  ignore-resolve-fail: true

proxy-groups:
  - name: èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies: [âš¡ å»¶è¿Ÿä¼˜é€‰]
    include-all: true
    icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Rocket.png"

  - name: å»¶è¿Ÿä¼˜é€‰
    type: url-test
    include-all: true
    url: https://www.gstatic.com/generate_204
    exclude-type: direct|reject
    interval: 300
    tolerance: 20
    lazy: true
    icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/Urltest.png"

  - name: ä¸‹è½½ç¨‹åº
    type: select
    proxies: [âœ”ï¸ å…¨å±€ç›´è¿,ğŸš€ èŠ‚ç‚¹é€‰æ‹©]
    icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Download.png"

  - name: å¹¿å‘Šæ‹¦æˆª
    type: select
    proxies: [âŒ æ‹’ç»è¿æ¥,â„ï¸ é™é»˜æ‹’ç»,âœ”ï¸ å…¨å±€ç›´è¿]
    icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hijacking.png"

  - name: BiliBili
    type: select
    proxies: [âœ”ï¸ å…¨å±€ç›´è¿,ğŸš€ èŠ‚ç‚¹é€‰æ‹©]
    icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/Bili.png"

  - name: å°é»‘ç›’
    type: select
    proxies: [âœ”ï¸ å…¨å±€ç›´è¿,ğŸš€ èŠ‚ç‚¹é€‰æ‹©]
    icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/heybox.png"

  - name: Telegram
    type: select
    proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©,âœ”ï¸ å…¨å±€ç›´è¿]
    icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/Telegram.png"

  - name: GitHub
    type: select
    proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©,âœ”ï¸ å…¨å±€ç›´è¿]
    icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/GitHub.png"

  - name: Pixiv
    type: select
    proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©,âœ”ï¸ å…¨å±€ç›´è¿]
    icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/Wallless.png"

  - name: Google
    type: select
    proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©,âœ”ï¸ å…¨å±€ç›´è¿]
    icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png"

  - name: EhViewer
    type: select
    proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©,âœ”ï¸ å…¨å±€ç›´è¿]
    icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/Xingmeng.png"

  - name: Twitter
    type: select
    proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©,âœ”ï¸ å…¨å±€ç›´è¿]
    icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/Twitter.png"

  - name: YouTube
    type: select
    proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©,âœ”ï¸ å…¨å±€ç›´è¿]
    icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/YouTube.png"

  - name: Steam
    type: select
    proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©,âœ”ï¸ å…¨å±€ç›´è¿]
    icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Steam.png"

  - name: å¤§é™†ç›´è¿
    type: select
    proxies: [âœ”ï¸ å…¨å±€ç›´è¿,ğŸš€ èŠ‚ç‚¹é€‰æ‹©]
    icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/China.png"

  - name: GFW
    type: select
    proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©,âœ”ï¸ å…¨å±€ç›´è¿]
    icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/China_Map.png"

  - name: æ¼ç½‘ä¹‹é±¼
    type: select
    proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©,âœ”ï¸ å…¨å±€ç›´è¿]
    icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Final.png"

#åˆ†éš”  ä»¥ä¸‹æ˜¯åœ°åŒºåˆ†ç»„,é»˜è®¤ä¸ºéšè—,æƒ³è¦æŠŠä»¥ä¸‹åœ°åŒºåœ¨APPå†…å¯è§†åŒ–,æŠŠ"hidden: true"æ”¹ä¸º"hidden: false"å°±è¡Œäº†
  - name: é¦™æ¸¯
    type: url-test
    include-all: true
    url: https://www.gstatic.com/generate_204
    exclude-type: direct
    interval: 300
    filter: "(?i)æ¸¯|hk|hongkong|hong kong"
    hidden: true
    icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png"

  - name: å°æ¹¾
    type: url-test
    include-all: true
    url: https://www.gstatic.com/generate_204
    exclude-type: direct
    interval: 300
    filter: "(?i)å°|tw|taiwan"
    hidden: true
    icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png"

  - name: æ—¥æœ¬
    type: url-test
    include-all: true
    url: https://www.gstatic.com/generate_204
    exclude-type: direct
    interval: 300
    filter: "(?i)æ—¥|jp|japan"
    hidden: true
    icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png"

  - name: ç¾å›½
    type: url-test
    include-all: true
    url: https://www.gstatic.com/generate_204
    exclude-type: direct
    interval: 300
    filter: "(?i)ç¾|us|unitedstates|united states"
    hidden: true
    icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png"

  - name: æ–°åŠ å¡
    type: url-test
    include-all: true
    url: https://www.gstatic.com/generate_204
    exclude-type: direct
    interval: 300
    filter: "(?i)(æ–°|sg|singapore)"
    hidden: true
    icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png"

#åˆ†éš”  ä»¥ä¸‹æ˜¯å†…ç½®ç­–ç•¥ç»„,ä¸è¦ä¹±åŠ¨
  - name: âœ”ï¸ å…¨å±€ç›´è¿
    type: select
    proxies: [DIRECT]
    hidden: true

  - name: âŒ æ‹’ç»è¿æ¥
    type: select
    proxies: [REJECT]
    hidden: true

  - name: â„ï¸ é™é»˜æ‹’ç»
    type: select
    proxies: [REJECT-DROP]
    hidden: true

  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies: [èŠ‚ç‚¹é€‰æ‹©]
    hidden: true

  - name: âš¡ å»¶è¿Ÿä¼˜é€‰
    type: select
    proxies: [å»¶è¿Ÿä¼˜é€‰]
    hidden: true

  - name: GLOBAL
    type: select
    proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©,âš¡ å»¶è¿Ÿä¼˜é€‰,âœ”ï¸ å…¨å±€ç›´è¿]
    hidden: false
    icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png"

#åˆ†éš”
#ç¬¬ä¸€åˆ—ä¸ºrule-set(å¼•ç”¨è§„åˆ™é›†),éœ€è¦é…åˆåé¢çš„rule-providers
#ç¬¬äºŒåˆ—ä¸ºrule-providersçš„åç§°
#ç¬¬ä¸‰åˆ—ä¸ºå‰é¢ä»£ç†ç»„çš„åç§°
rules:
  - RULE-SET,Lan,å¤§é™†ç›´è¿
  - RULE-SET,Direct,å¤§é™†ç›´è¿
  - RULE-SET,Category-Ads-All,å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,BiliBili,BiliBili
  - RULE-SET,HeyBox,å°é»‘ç›’
  - RULE-SET,Download,ä¸‹è½½ç¨‹åº
  - RULE-SET,GameDownloadCN,ä¸‹è½½ç¨‹åº
  - RULE-SET,SteamCN,å¤§é™†ç›´è¿
  - RULE-SET,Steam,Steam
  - RULE-SET,EHGallery,EhViewer
  - RULE-SET,GitHub,GitHub
  - RULE-SET,Google,Google
  - RULE-SET,Pixiv,Pixiv
  - RULE-SET,Twitter,Twitter
  - RULE-SET,YouTube,YouTube
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Hijacking,GFW
  - RULE-SET,ProxyLite,GFW

  - RULE-SET,CN_Domain,å¤§é™†ç›´è¿
  - RULE-SET,CN_IP,å¤§é™†ç›´è¿
  - MATCH,æ¼ç½‘ä¹‹é±¼

#åˆ†éš”  ä»¥ä¸‹çš„rule-providersä¸ä¸Šæ–¹çš„rulesé…åˆä½¿ç”¨
rule-providers:
  Download:
    type: http
    url: "https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/Download/Download.yaml"
    interval: 86400
    proxy: âš¡ å»¶è¿Ÿä¼˜é€‰
    behavior: classical
    format: yaml

  GameDownloadCN:
    type: http
    url: "https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/Game/GameDownloadCN/GameDownloadCN.yaml"
    interval: 86400
    proxy: âš¡ å»¶è¿Ÿä¼˜é€‰
    behavior: classical
    format: yaml

  Hijacking:
    type: http
    url: "https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/Hijacking/Hijacking_No_Resolve.yaml"
    interval: 86400
    proxy: âš¡ å»¶è¿Ÿä¼˜é€‰
    behavior: classical
    format: yaml

  Lan:
    type: http
    url: "https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/Lan/Lan_No_Resolve.yaml"
    interval: 86400
    proxy: âš¡ å»¶è¿Ÿä¼˜é€‰
    behavior: classical
    format: yaml

  Category-Ads-All:
    type: http
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ads-all.yaml"
    interval: 86400
    proxy: âš¡ å»¶è¿Ÿä¼˜é€‰
    behavior: domain
    format: yaml

  SteamCN:
    type: http
    url: "https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/SteamCN/SteamCN.yaml"
    interval: 86400
    proxy: âš¡ å»¶è¿Ÿä¼˜é€‰
    behavior: classical
    format: yaml

  Steam:
    type: http
    url: "https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/Steam/Steam.yaml"
    interval: 86400
    proxy: âš¡ å»¶è¿Ÿä¼˜é€‰
    behavior: classical
    format: yaml

  ProxyLite:
    type: http
    url: "https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/ProxyLite/ProxyLite_No_Resolve.yaml"
    interval: 86400
    proxy: âš¡ å»¶è¿Ÿä¼˜é€‰
    behavior: classical
    format: yaml

  Direct:
    type: http
    url: "https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/Direct/Direct.yaml"
    interval: 86400
    proxy: âš¡ å»¶è¿Ÿä¼˜é€‰
    behavior: classical
    format: yaml

  BiliBili:
    type: http
    url: "https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/BiliBili/BiliBili_No_Resolve.yaml"
    interval: 86400
    proxy: âš¡ å»¶è¿Ÿä¼˜é€‰
    behavior: classical
    format: yaml

  GitHub:
    type: http
    url: "https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/GitHub/GitHub.yaml"
    interval: 86400
    proxy: âš¡ å»¶è¿Ÿä¼˜é€‰
    behavior: classical
    format: yaml

  Google:
    type: http
    url: "https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/Google/Google_No_Resolve.yaml"
    interval: 86400
    proxy: âš¡ å»¶è¿Ÿä¼˜é€‰
    behavior: classical
    format: yaml

  YouTube:
    type: http
    url: "https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/YouTube/YouTube_No_Resolve.yaml"
    interval: 86400
    proxy: âš¡ å»¶è¿Ÿä¼˜é€‰
    behavior: classical
    format: yaml

  Pixiv:
    type: http
    url: "https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/Pixiv/Pixiv.yaml"
    interval: 86400
    proxy: âš¡ å»¶è¿Ÿä¼˜é€‰
    behavior: classical
    format: yaml

  Twitter:
    type: http
    url: "https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/Twitter/Twitter_No_Resolve.yaml"
    interval: 86400
    proxy: âš¡ å»¶è¿Ÿä¼˜é€‰
    behavior: classical
    format: yaml

  EHGallery:
    type: http
    url: "https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/EHGallery/EHGallery_No_Resolve.yaml"
    interval: 86400
    proxy: âš¡ å»¶è¿Ÿä¼˜é€‰
    behavior: classical
    format: yaml

  CN_IP:
    type: http
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geoip/cn.yaml"
    interval: 86400
    proxy: âš¡ å»¶è¿Ÿä¼˜é€‰
    behavior: ipcidr
    format: yaml

  CN_Domain:
    type: http
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geosite/cn.yaml"
    interval: 86400
    proxy: âš¡ å»¶è¿Ÿä¼˜é€‰
    behavior: domain
    format: yaml

  HeyBox:
    type: http
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/xiaoheihe.yaml"
    interval: 86400
    proxy: âš¡ å»¶è¿Ÿä¼˜é€‰
    behavior: domain
    format: yaml
  
  Telegram:
    type: http
    url: "https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/Telegram/Telegram_No_Resolve.yaml"
    interval: 86400
    proxy: âš¡ å»¶è¿Ÿä¼˜é€‰
    behavior: domain
    format: yaml
