####### é”šç‚¹ start #######
#è®¢é˜…æ›´æ–°å’Œå»¶è¿Ÿæµ‹è¯•ç›¸å…³
p: &p {type: http, interval: 86400, health-check: {enable: true, url: "https://www.gstatic.com/generate_204", interval: 300}, proxy: DIRECT, override: {udp: true, down: "50 Mbps", up: "10 Mbps", tfo: true, skip-cert-verify: true}}

# ç­–ç•¥ç»„ç›¸å…³
pr: &pr {type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, ğŸŸ¢ å…¨å±€ç›´è¿, ğŸ”´ æ‹’ç»è¿æ¥, ğŸ’¤ é™é»˜æ‹’ç», ğŸ”˜ ç»•è¿‡è§„åˆ™, é¦™æ¸¯è‡ªåŠ¨, å°æ¹¾è‡ªåŠ¨, æ–°åŠ å¡è‡ªåŠ¨, æ—¥æœ¬è‡ªåŠ¨, ç¾å›½è‡ªåŠ¨]}

#è§„åˆ™é›†ç›¸å…³
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: yaml}
####### é”šç‚¹ end #######

proxy-providers:
#æŠŠå¤åˆ¶çš„è®¢é˜…åœ°å€ç²˜è´´åˆ°ä¸‹é¢çš„ url é‡Œ
  Airport:
    url: ""
    <<: *p

mixed-port: 7890
port: 7891
socks-port: 7892
ipv6: true
allow-lan: true
bind-address: "*"
mode: rule
log-level: warning
unified-delay: true
keep-alive-interval: 15
keep-alive-idle: 300
disable-keep-alive: false
tcp-concurrent: true

external-controller: 127.0.0.1:9090
external-controller-cors:
  allow-origins:
    - '*'
  allow-private-network: true
external-ui: ui
external-ui-name: xd
secret: ""
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

find-process-mode: strict
global-client-fingerprint: chrome
global-ua: clash.meta

profile:
  store-selected: true
  store-fake-ip: true

#åˆ†éš”  å—…æ¢åŠŸèƒ½ä¸€èˆ¬äººç”¨ä¸åˆ°,å…·ä½“çœ‹è‡ªå·±éœ€æ±‚ (æŠŠä»¥ä¸‹çš„#å·åˆ é™¤å³å¯)
#sniffer:
  #enable: true
  #force-dns-mapping: true
  #parse-pure-ip: true
  #override-destination: true
  #sniff:
   # HTTP:
      #ports: [80, 8080-8880]
      #override-destination: true
    #TLS:
      #ports: [443, 8443]
    #QUIC:
      #ports: [443, 8443]
  #force-domain:
   # - +.v2ex.com
  #skip-domain:
    #- "Mijia Cloud"
    #- "+.push.apple.com"
    #- "+.apple.com"
    #- "+.dlg.io.mi.com"

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - any:53
    - tcp://any:53
  device: mihomo
  mtu: 4000
  strict-route: true
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

dns:
  enable: true
  cache-algorithm: arc
#åˆ†éš”  è¿æ¥éµå®ˆè·¯ç”±è§„åˆ™,ä¸å»ºè®®å’Œ"prefer-h3"ä¸€èµ·ä½¿ç”¨
  respect-rules: true
  ipv6: false
  ipv6-timeout: 300
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - rule-set:private_domain
  nameserver-policy:
    'rule-set:private_domain,cn_domain':
      - 223.5.5.5
      - 119.29.29.29
    'rule-set:geolocation-!cn':
      - tls://8.8.4.4#èŠ‚ç‚¹é€‰æ‹©
      - tls://1.1.1.1#èŠ‚ç‚¹é€‰æ‹©
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  direct-nameserver:
    - 223.5.5.5
  default-nameserver-follow-policy: false
  proxy-server-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - 223.5.5.5
    - 119.29.29.29

proxy-groups:
- {name: èŠ‚ç‚¹é€‰æ‹©, type: select, proxies: [âš¡ å»¶è¿Ÿä¼˜é€‰, é¦™æ¸¯è‡ªåŠ¨, å°æ¹¾è‡ªåŠ¨, æ–°åŠ å¡è‡ªåŠ¨, æ—¥æœ¬è‡ªåŠ¨, ç¾å›½è‡ªåŠ¨], include-all: true, exclude-filter: "å®˜ç½‘|é‡ç½®|åˆ°æœŸ|å‰©ä½™|äº¤æµ|å¤±è”|è¶…æ—¶|é‡å¯|é£è¡Œ|æ›´æ–°", icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Rocket.png"}
- {name: å»¶è¿Ÿä¼˜é€‰, type: url-test, include-all: true, exclude-type: direct, tolerance: 25, exclude-filter: "å®˜ç½‘|é‡ç½®|åˆ°æœŸ|å‰©ä½™|äº¤æµ|å¤±è”|è¶…æ—¶|é‡å¯|é£è¡Œ|æ›´æ–°", icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/Urltest.png"}
- {name: ä¸‹è½½ç¨‹åº, <<: *pr, icon: "https://github.com/Vbaethon/HOMOMIX/blob/main/Icon/Color/Large/Download.png?raw=true"}
- {name: å¹¿å‘Šæ‹¦æˆª, <<: *pr, icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hijacking.png"}
- {name: å“”å“©å“”å“©, <<: *pr, icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/Bili.png"}
- {name: å°é»‘ç›’, <<: *pr, icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/heybox.png"}
- {name: Telegram, <<: *pr, icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/Telegram.png"}
- {name: GitHub, <<: *pr, icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/GitHub.png"}
- {name: Pixiv, <<: *pr, icon: "https://github.com/Vbaethon/HOMOMIX/blob/main/Icon/Color/Large/Pixiv.png?raw=true"}
- {name: Steam, <<: *pr, icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Steam.png"}
- {name: EhViewer, <<: *pr, icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Rainbow.png"}
- {name: ç¦æ¼«å¤©å ‚, <<: *pr, icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/Flower.png"}
- {name: Twitter, <<: *pr, icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/Twitter.png"}
- {name: YouTube, <<: *pr, icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/YouTube.png"}
- {name: Google, <<: *pr, icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png"}
- {name: Microsoft, <<: *pr, icon: "https://github.com/Vbaethon/HOMOMIX/blob/main/Icon/Color/Large/Microsoft.png?raw=true"}
- {name: å¤§é™†ç›´è¿, <<: *pr, icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/China_Map.png"}
- {name: GFW, <<: *pr, icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png"}
- {name: æ¼ç½‘ä¹‹é±¼, <<: *pr, icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Final.png"}
#åˆ†éš”  ä»¥ä¸‹æ˜¯åœ°åŒºåˆ†ç»„
- {name: é¦™æ¸¯è‡ªåŠ¨,type: url-test, include-all: true, exclude-type: direct, filter: "(?i)(æ¸¯|hk|hongkong|hong kong)", icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png"}
- {name: å°æ¹¾è‡ªåŠ¨, type: url-test, include-all: true, exclude-type: direct, filter: "(?i)å°|tw|taiwan", icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png"}
- {name: æ–°åŠ å¡è‡ªåŠ¨, type: url-test, include-all: true, exclude-type: direct, filter: "(?i)(æ–°|sg|singapore)", icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png"}
- {name: æ—¥æœ¬è‡ªåŠ¨, type: url-test, include-all: true, exclude-type: direct, filter: "(?i)æ—¥|jp|japan", icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png"}
- {name: ç¾å›½è‡ªåŠ¨, type: url-test, include-all: true, exclude-type: direct, filter: "(?i)ç¾|us|unitedstates|united states", icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png"}
#åˆ†éš”  ä»¥ä¸‹æ˜¯éšè—ç­–ç•¥ç»„,ä¸è¦ä¹±åŠ¨
- {name: ğŸŸ¢ å…¨å±€ç›´è¿, type: select, proxies: [DIRECT], hidden: true}
- {name: ğŸ”´ æ‹’ç»è¿æ¥, type: select, proxies: [REJECT], hidden: true}
- {name: ğŸ’¤ é™é»˜æ‹’ç», type: select, proxies: [REJECT-DROP], hidden: true}
- {name: ğŸ”˜ ç»•è¿‡è§„åˆ™, type: select, proxies: [PASS], hidden: true}
- {name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©, type: select, proxies: [èŠ‚ç‚¹é€‰æ‹©], hidden: true}
- {name: âš¡ å»¶è¿Ÿä¼˜é€‰, type: select, proxies: [å»¶è¿Ÿä¼˜é€‰], hidden: true}

#åˆ†éš”
#ç¬¬ä¸€åˆ—ä¸ºrule-set(å¼•ç”¨è§„åˆ™é›†),éœ€è¦é…åˆåé¢çš„rule-providers
#ç¬¬äºŒåˆ—ä¸ºrule-providersçš„åç§°
#ç¬¬ä¸‰åˆ—ä¸ºä¹‹å‰ç­–ç•¥ç»„çš„åç§°
rules:
  - RULE-SET,private_ip,å¤§é™†ç›´è¿
  - RULE-SET,private_domain,å¤§é™†ç›´è¿
  - RULE-SET,category-httpdns-cn,å¤§é™†ç›´è¿
  - RULE-SET,awavenue_ads_rule,å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,category-ads-all,å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,download,ä¸‹è½½ç¨‹åº
  - RULE-SET,game_download_cn,ä¸‹è½½ç¨‹åº
  - RULE-SET,bilibili_domain,å“”å“©å“”å“©
  - RULE-SET,xiaoheihe_domain,å°é»‘ç›’
  - RULE-SET,steam@cn_domain,å¤§é™†ç›´è¿
  - RULE-SET,steam_domain,Steam
  - RULE-SET,18comic_domain,ç¦æ¼«å¤©å ‚
  - RULE-SET,ehentai_domain,EhViewer
  - RULE-SET,github_domain,GitHub
  - RULE-SET,youtube_domain,YouTube
  - RULE-SET,telegram_domain,Telegram
  - RULE-SET,twitter_domain,Twitter
  - RULE-SET,pixiv_domain,Pixiv
  - RULE-SET,google_domain,Google
  - RULE-SET,microsoft_domain,Microsoft

  - RULE-SET,bilibili_ip,å“”å“©å“”å“©
  - RULE-SET,telegram_ip,Telegram
  - RULE-SET,twitter_ip,Twitter
  - RULE-SET,google_ip,Google

  - RULE-SET,cn_domain,å¤§é™†ç›´è¿
  - RULE-SET,cn_ip,å¤§é™†ç›´è¿
  - RULE-SET,geolocation-!cn,GFW
  - MATCH,æ¼ç½‘ä¹‹é±¼

#åˆ†éš”  ä»¥ä¸‹çš„rule-providersä¸ä¸Šæ–¹çš„rulesé…åˆä½¿ç”¨
rule-providers:
  bilibili_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bilibili.mrs"}
  18comic_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/18comic.mrs"}
  ehentai_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ehentai.mrs"}
  github_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
  google_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  microsoft_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  pixiv_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/pixiv.mrs"}
  steam_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.mrs"}
  steam@cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam@cn.mrs"}
  telegram_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  twitter_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/x.mrs"}
  xiaoheihe_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/xiaoheihe.mrs"}
  youtube_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
  category-ads-all: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ads-all.mrs"}
  category-httpdns-cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-httpdns-cn.mrs"}
  geolocation-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  private_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}

  bilibili_ip: { <<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geoip/bilibili.mrs"}
  google_ip: { <<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geoip/google.mrs"}
  telegram_ip: { <<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geoip/telegram.mrs"}
  twitter_ip: { <<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geoip/twitter.mrs"}
  private_ip: {<<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geoip/private.mrs"}
  cn_ip: { <<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geoip/cn.mrs"}

  download: { <<: *class, url: "https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/Download/Download.yaml"}
  game_download_cn: { <<: *class, url: "https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/Game/GameDownloadCN/GameDownloadCN.yaml"}
  awavenue_ads_rule: { <<: *class, url: "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash-Classical.yaml"}
